/**
 * USBC Standard League Schedules
 * Source: Provided by user via images (Professional USBC Templates)
 */

export interface MatchupTemplate {
    teamA: number;
    teamB: number;
    lanePairIndex: number; // 0-based index (e.g., 0 = first lane pair in range)
}

export interface LeagueTemplate {
    teamCount: number;
    rounds: MatchupTemplate[][];
}

export const LEAGUE_TEMPLATES: Record<number, LeagueTemplate> = {
    4: {
        teamCount: 4,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }],
            [{ teamA: 3, teamB: 1, lanePairIndex: 0 }, { teamA: 4, teamB: 2, lanePairIndex: 1 }],
            [{ teamA: 2, teamB: 3, lanePairIndex: 0 }, { teamA: 1, teamB: 4, lanePairIndex: 1 }],
        ]
    },
    6: {
        teamCount: 6,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }],
            [{ teamA: 5, teamB: 4, lanePairIndex: 0 }, { teamA: 1, teamB: 6, lanePairIndex: 1 }, { teamA: 2, teamB: 3, lanePairIndex: 2 }],
            [{ teamA: 3, teamB: 1, lanePairIndex: 0 }, { teamA: 2, teamB: 5, lanePairIndex: 1 }, { teamA: 6, teamB: 4, lanePairIndex: 2 }],
            [{ teamA: 2, teamB: 6, lanePairIndex: 0 }, { teamA: 4, teamB: 1, lanePairIndex: 1 }, { teamA: 3, teamB: 5, lanePairIndex: 2 }],
            [{ teamA: 1, teamB: 5, lanePairIndex: 0 }, { teamA: 6, teamB: 3, lanePairIndex: 1 }, { teamA: 4, teamB: 2, lanePairIndex: 2 }],
        ]
    },
    8: {
        teamCount: 8,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }],
            [{ teamA: 6, teamB: 8, lanePairIndex: 0 }, { teamA: 5, teamB: 7, lanePairIndex: 1 }, { teamA: 2, teamB: 4, lanePairIndex: 2 }, { teamA: 1, teamB: 3, lanePairIndex: 3 }],
            [{ teamA: 5, teamB: 4, lanePairIndex: 0 }, { teamA: 1, teamB: 8, lanePairIndex: 1 }, { teamA: 7, teamB: 3, lanePairIndex: 2 }, { teamA: 2, teamB: 6, lanePairIndex: 3 }],
            [{ teamA: 3, teamB: 6, lanePairIndex: 0 }, { teamA: 7, teamB: 2, lanePairIndex: 1 }, { teamA: 1, teamB: 5, lanePairIndex: 2 }, { teamA: 8, teamB: 4, lanePairIndex: 3 }],
            [{ teamA: 7, teamB: 1, lanePairIndex: 0 }, { teamA: 4, teamB: 6, lanePairIndex: 1 }, { teamA: 3, teamB: 8, lanePairIndex: 2 }, { teamA: 5, teamB: 2, lanePairIndex: 3 }],
            [{ teamA: 2, teamB: 3, lanePairIndex: 0 }, { teamA: 8, teamB: 5, lanePairIndex: 1 }, { teamA: 4, teamB: 1, lanePairIndex: 2 }, { teamA: 6, teamB: 7, lanePairIndex: 3 }],
            [{ teamA: 4, teamB: 7, lanePairIndex: 0 }, { teamA: 6, teamB: 1, lanePairIndex: 1 }, { teamA: 8, teamB: 2, lanePairIndex: 2 }, { teamA: 3, teamB: 5, lanePairIndex: 3 }],
        ]
    },
    10: {
        teamCount: 10,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }, { teamA: 9, teamB: 10, lanePairIndex: 4 }],
            [{ teamA: 7, teamB: 3, lanePairIndex: 0 }, { teamA: 1, teamB: 6, lanePairIndex: 1 }, { teamA: 2, teamB: 9, lanePairIndex: 2 }, { teamA: 5, teamB: 10, lanePairIndex: 3 }, { teamA: 8, teamB: 4, lanePairIndex: 4 }],
            [{ teamA: 4, teamB: 5, lanePairIndex: 0 }, { teamA: 9, teamB: 8, lanePairIndex: 1 }, { teamA: 10, teamB: 1, lanePairIndex: 2 }, { teamA: 3, teamB: 2, lanePairIndex: 3 }, { teamA: 6, teamB: 7, lanePairIndex: 4 }],
            [{ teamA: 9, teamB: 1, lanePairIndex: 0 }, { teamA: 5, teamB: 3, lanePairIndex: 1 }, { teamA: 4, teamB: 7, lanePairIndex: 2 }, { teamA: 8, teamB: 6, lanePairIndex: 3 }, { teamA: 10, teamB: 2, lanePairIndex: 4 }],
            [{ teamA: 10, teamB: 7, lanePairIndex: 0 }, { teamA: 6, teamB: 2, lanePairIndex: 1 }, { teamA: 8, teamB: 3, lanePairIndex: 2 }, { teamA: 4, teamB: 1, lanePairIndex: 3 }, { teamA: 5, teamB: 9, lanePairIndex: 4 }],
            [{ teamA: 5, teamB: 8, lanePairIndex: 0 }, { teamA: 4, teamB: 10, lanePairIndex: 1 }, { teamA: 7, teamB: 2, lanePairIndex: 2 }, { teamA: 6, teamB: 9, lanePairIndex: 3 }, { teamA: 1, teamB: 3, lanePairIndex: 4 }],
            [{ teamA: 6, teamB: 4, lanePairIndex: 0 }, { teamA: 7, teamB: 9, lanePairIndex: 1 }, { teamA: 1, teamB: 5, lanePairIndex: 2 }, { teamA: 10, teamB: 3, lanePairIndex: 3 }, { teamA: 2, teamB: 8, lanePairIndex: 4 }],
            [{ teamA: 3, teamB: 9, lanePairIndex: 0 }, { teamA: 8, teamB: 1, lanePairIndex: 1 }, { teamA: 6, teamB: 10, lanePairIndex: 2 }, { teamA: 2, teamB: 4, lanePairIndex: 3 }, { teamA: 7, teamB: 5, lanePairIndex: 4 }],
            [{ teamA: 8, teamB: 10, lanePairIndex: 0 }, { teamA: 2, teamB: 5, lanePairIndex: 1 }, { teamA: 9, teamB: 4, lanePairIndex: 2 }, { teamA: 1, teamB: 7, lanePairIndex: 3 }, { teamA: 3, teamB: 6, lanePairIndex: 4 }],
        ]
    },
    12: {
        teamCount: 12,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }, { teamA: 9, teamB: 10, lanePairIndex: 4 }, { teamA: 11, teamB: 12, lanePairIndex: 5 }],
            [{ teamA: 4, teamB: 5, lanePairIndex: 0 }, { teamA: 6, teamB: 2, lanePairIndex: 1 }, { teamA: 12, teamB: 3, lanePairIndex: 2 }, { teamA: 9, teamB: 11, lanePairIndex: 3 }, { teamA: 1, teamB: 7, lanePairIndex: 4 }, { teamA: 10, teamB: 8, lanePairIndex: 5 }],
            [{ teamA: 9, teamB: 3, lanePairIndex: 0 }, { teamA: 1, teamB: 10, lanePairIndex: 1 }, { teamA: 11, teamB: 4, lanePairIndex: 2 }, { teamA: 5, teamB: 12, lanePairIndex: 3 }, { teamA: 8, teamB: 2, lanePairIndex: 4 }, { teamA: 6, teamB: 7, lanePairIndex: 5 }],
            [{ teamA: 7, teamB: 12, lanePairIndex: 0 }, { teamA: 5, teamB: 8, lanePairIndex: 1 }, { teamA: 9, teamB: 2, lanePairIndex: 2 }, { teamA: 10, teamB: 4, lanePairIndex: 3 }, { teamA: 11, teamB: 6, lanePairIndex: 4 }, { teamA: 1, teamB: 3, lanePairIndex: 5 }],
            [{ teamA: 11, teamB: 8, lanePairIndex: 0 }, { teamA: 9, teamB: 7, lanePairIndex: 1 }, { teamA: 1, teamB: 5, lanePairIndex: 2 }, { teamA: 6, teamB: 3, lanePairIndex: 3 }, { teamA: 10, teamB: 12, lanePairIndex: 4 }, { teamA: 2, teamB: 4, lanePairIndex: 5 }],
            [{ teamA: 10, teamB: 6, lanePairIndex: 0 }, { teamA: 11, teamB: 1, lanePairIndex: 1 }, { teamA: 3, teamB: 8, lanePairIndex: 2 }, { teamA: 12, teamB: 2, lanePairIndex: 3 }, { teamA: 7, teamB: 4, lanePairIndex: 4 }, { teamA: 9, teamB: 5, lanePairIndex: 5 }],
            [{ teamA: 5, teamB: 7, lanePairIndex: 0 }, { teamA: 4, teamB: 12, lanePairIndex: 1 }, { teamA: 2, teamB: 10, lanePairIndex: 2 }, { teamA: 1, teamB: 9, lanePairIndex: 3 }, { teamA: 6, teamB: 8, lanePairIndex: 4 }, { teamA: 3, teamB: 11, lanePairIndex: 5 }],
            [{ teamA: 12, teamB: 9, lanePairIndex: 0 }, { teamA: 10, teamB: 5, lanePairIndex: 1 }, { teamA: 7, teamB: 11, lanePairIndex: 2 }, { teamA: 4, teamB: 6, lanePairIndex: 3 }, { teamA: 2, teamB: 3, lanePairIndex: 4 }, { teamA: 8, teamB: 1, lanePairIndex: 5 }],
            [{ teamA: 6, teamB: 1, lanePairIndex: 0 }, { teamA: 2, teamB: 11, lanePairIndex: 1 }, { teamA: 8, teamB: 12, lanePairIndex: 2 }, { teamA: 3, teamB: 5, lanePairIndex: 3 }, { teamA: 4, teamB: 9, lanePairIndex: 4 }, { teamA: 7, teamB: 10, lanePairIndex: 5 }],
            [{ teamA: 3, teamB: 10, lanePairIndex: 0 }, { teamA: 8, teamB: 9, lanePairIndex: 1 }, { teamA: 4, teamB: 1, lanePairIndex: 2 }, { teamA: 2, teamB: 7, lanePairIndex: 3 }, { teamA: 5, teamB: 11, lanePairIndex: 4 }, { teamA: 12, teamB: 6, lanePairIndex: 5 }],
            [{ teamA: 8, teamB: 4, lanePairIndex: 0 }, { teamA: 7, teamB: 3, lanePairIndex: 1 }, { teamA: 6, teamB: 9, lanePairIndex: 2 }, { teamA: 11, teamB: 10, lanePairIndex: 3 }, { teamA: 12, teamB: 1, lanePairIndex: 4 }, { teamA: 5, teamB: 2, lanePairIndex: 5 }],
        ]
    },
    14: {
        teamCount: 14,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }, { teamA: 9, teamB: 10, lanePairIndex: 4 }, { teamA: 11, teamB: 12, lanePairIndex: 5 }, { teamA: 13, teamB: 14, lanePairIndex: 6 }],
            [{ teamA: 12, teamB: 5, lanePairIndex: 0 }, { teamA: 13, teamB: 2, lanePairIndex: 1 }, { teamA: 14, teamB: 7, lanePairIndex: 2 }, { teamA: 9, teamB: 6, lanePairIndex: 3 }, { teamA: 8, teamB: 11, lanePairIndex: 4 }, { teamA: 10, teamB: 1, lanePairIndex: 5 }, { teamA: 3, teamB: 4, lanePairIndex: 6 }],
            [{ teamA: 9, teamB: 8, lanePairIndex: 0 }, { teamA: 10, teamB: 12, lanePairIndex: 1 }, { teamA: 11, teamB: 1, lanePairIndex: 2 }, { teamA: 13, teamB: 3, lanePairIndex: 3 }, { teamA: 5, teamB: 2, lanePairIndex: 4 }, { teamA: 4, teamB: 14, lanePairIndex: 5 }, { teamA: 7, teamB: 6, lanePairIndex: 6 }],
            [{ teamA: 11, teamB: 14, lanePairIndex: 0 }, { teamA: 1, teamB: 6, lanePairIndex: 1 }, { teamA: 4, teamB: 9, lanePairIndex: 2 }, { teamA: 10, teamB: 8, lanePairIndex: 3 }, { teamA: 12, teamB: 7, lanePairIndex: 4 }, { teamA: 2, teamB: 13, lanePairIndex: 5 }, { teamA: 5, teamB: 3, lanePairIndex: 6 }],
            [{ teamA: 10, teamB: 5, lanePairIndex: 0 }, { teamA: 12, teamB: 7, lanePairIndex: 1 }, { teamA: 13, teamB: 1, lanePairIndex: 2 }, { teamA: 14, teamB: 3, lanePairIndex: 3 }, { teamA: 4, teamB: 6, lanePairIndex: 4 }, { teamA: 8, teamB: 2, lanePairIndex: 5 }, { teamA: 9, teamB: 11, lanePairIndex: 6 }],
            [{ teamA: 13, teamB: 10, lanePairIndex: 0 }, { teamA: 5, teamB: 12, lanePairIndex: 1 }, { teamA: 9, teamB: 3, lanePairIndex: 2 }, { teamA: 2, teamB: 7, lanePairIndex: 3 }, { teamA: 1, teamB: 6, lanePairIndex: 4 }, { teamA: 8, teamB: 4, lanePairIndex: 5 }, { teamA: 14, teamB: 11, lanePairIndex: 6 }],
            [{ teamA: 6, teamB: 8, lanePairIndex: 0 }, { teamA: 9, teamB: 7, lanePairIndex: 1 }, { teamA: 4, teamB: 10, lanePairIndex: 2 }, { teamA: 1, teamB: 11, lanePairIndex: 3 }, { teamA: 3, teamB: 14, lanePairIndex: 4 }, { teamA: 13, teamB: 5, lanePairIndex: 5 }, { teamA: 12, teamB: 2, lanePairIndex: 6 }],
            [{ teamA: 5, teamB: 1, lanePairIndex: 0 }, { teamA: 10, teamB: 6, lanePairIndex: 1 }, { teamA: 3, teamB: 8, lanePairIndex: 2 }, { teamA: 12, teamB: 13, lanePairIndex: 3 }, { teamA: 11, teamB: 9, lanePairIndex: 4 }, { teamA: 14, teamB: 2, lanePairIndex: 5 }, { teamA: 7, teamB: 4, lanePairIndex: 6 }],
            [{ teamA: 3, teamB: 12, lanePairIndex: 0 }, { teamA: 11, teamB: 5, lanePairIndex: 1 }, { teamA: 13, teamB: 1, lanePairIndex: 2 }, { teamA: 14, teamB: 8, lanePairIndex: 3 }, { teamA: 6, teamB: 2, lanePairIndex: 4 }, { teamA: 4, teamB: 9, lanePairIndex: 5 }, { teamA: 10, teamB: 7, lanePairIndex: 6 }],
            [{ teamA: 4, teamB: 11, lanePairIndex: 0 }, { teamA: 14, teamB: 10, lanePairIndex: 1 }, { teamA: 7, teamB: 8, lanePairIndex: 2 }, { teamA: 2, teamB: 5, lanePairIndex: 3 }, { teamA: 1, teamB: 3, lanePairIndex: 4 }, { teamA: 9, teamB: 13, lanePairIndex: 5 }, { teamA: 6, teamB: 12, lanePairIndex: 6 }],
            [{ teamA: 9, teamB: 14, lanePairIndex: 0 }, { teamA: 4, teamB: 1, lanePairIndex: 1 }, { teamA: 11, teamB: 10, lanePairIndex: 2 }, { teamA: 5, teamB: 2, lanePairIndex: 3 }, { teamA: 13, teamB: 3, lanePairIndex: 4 }, { teamA: 6, teamB: 12, lanePairIndex: 5 }, { teamA: 8, teamB: 7, lanePairIndex: 6 }],
            [{ teamA: 11, teamB: 13, lanePairIndex: 0 }, { teamA: 1, teamB: 5, lanePairIndex: 1 }, { teamA: 10, teamB: 12, lanePairIndex: 2 }, { teamA: 3, teamB: 14, lanePairIndex: 3 }, { teamA: 2, teamB: 4, lanePairIndex: 4 }, { teamA: 7, teamB: 9, lanePairIndex: 5 }, { teamA: 6, teamB: 8, lanePairIndex: 6 }],
            [{ teamA: 14, teamB: 6, lanePairIndex: 0 }, { teamA: 2, teamB: 1, lanePairIndex: 1 }, { teamA: 3, teamB: 5, lanePairIndex: 2 }, { teamA: 4, teamB: 7, lanePairIndex: 3 }, { teamA: 8, teamB: 10, lanePairIndex: 4 }, { teamA: 11, teamB: 9, lanePairIndex: 5 }, { teamA: 12, teamB: 13, lanePairIndex: 6 }],
        ]
    },
    16: {
        teamCount: 16,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }, { teamA: 9, teamB: 10, lanePairIndex: 4 }, { teamA: 11, teamB: 12, lanePairIndex: 5 }, { teamA: 13, teamB: 14, lanePairIndex: 6 }, { teamA: 15, teamB: 16, lanePairIndex: 7 }],
            [{ teamA: 13, teamB: 12, lanePairIndex: 0 }, { teamA: 6, teamB: 15, lanePairIndex: 1 }, { teamA: 8, teamB: 3, lanePairIndex: 2 }, { teamA: 10, teamB: 5, lanePairIndex: 3 }, { teamA: 11, teamB: 7, lanePairIndex: 4 }, { teamA: 9, teamB: 2, lanePairIndex: 5 }, { teamA: 1, teamB: 16, lanePairIndex: 6 }, { teamA: 4, teamB: 14, lanePairIndex: 7 }],
            [{ teamA: 9, teamB: 16, lanePairIndex: 0 }, { teamA: 8, teamB: 14, lanePairIndex: 1 }, { teamA: 15, teamB: 10, lanePairIndex: 2 }, { teamA: 11, teamB: 3, lanePairIndex: 3 }, { teamA: 5, teamB: 2, lanePairIndex: 4 }, { teamA: 7, teamB: 13, lanePairIndex: 5 }, { teamA: 4, teamB: 12, lanePairIndex: 6 }, { teamA: 1, teamB: 6, lanePairIndex: 7 }],
            [{ teamA: 7, teamB: 4, lanePairIndex: 0 }, { teamA: 1, teamB: 10, lanePairIndex: 1 }, { teamA: 14, teamB: 11, lanePairIndex: 2 }, { teamA: 15, teamB: 2, lanePairIndex: 3 }, { teamA: 3, teamB: 13, lanePairIndex: 4 }, { teamA: 16, teamB: 5, lanePairIndex: 5 }, { teamA: 6, teamB: 9, lanePairIndex: 6 }, { teamA: 12, teamB: 8, lanePairIndex: 7 }],
            [{ teamA: 8, teamB: 5, lanePairIndex: 0 }, { teamA: 2, teamB: 12, lanePairIndex: 1 }, { teamA: 13, teamB: 1, lanePairIndex: 2 }, { teamA: 14, teamB: 16, lanePairIndex: 3 }, { teamA: 15, teamB: 4, lanePairIndex: 4 }, { teamA: 6, teamB: 3, lanePairIndex: 5 }, { teamA: 10, teamB: 7, lanePairIndex: 6 }, { teamA: 9, teamB: 11, lanePairIndex: 7 }],
            [{ teamA: 10, teamB: 3, lanePairIndex: 0 }, { teamA: 9, teamB: 13, lanePairIndex: 1 }, { teamA: 12, teamB: 16, lanePairIndex: 2 }, { teamA: 4, teamB: 1, lanePairIndex: 3 }, { teamA: 6, teamB: 14, lanePairIndex: 4 }, { teamA: 15, teamB: 8, lanePairIndex: 5 }, { teamA: 5, teamB: 11, lanePairIndex: 6 }, { teamA: 2, teamB: 7, lanePairIndex: 7 }],
            [{ teamA: 15, teamB: 11, lanePairIndex: 0 }, { teamA: 7, teamB: 16, lanePairIndex: 1 }, { teamA: 4, teamB: 9, lanePairIndex: 2 }, { teamA: 12, teamB: 6, lanePairIndex: 3 }, { teamA: 8, teamB: 1, lanePairIndex: 4 }, { teamA: 10, teamB: 14, lanePairIndex: 5 }, { teamA: 3, teamB: 2, lanePairIndex: 6 }, { teamA: 13, teamB: 5, lanePairIndex: 7 }],
            [{ teamA: 6, teamB: 7, lanePairIndex: 0 }, { teamA: 11, teamB: 1, lanePairIndex: 1 }, { teamA: 2, teamB: 14, lanePairIndex: 2 }, { teamA: 8, teamB: 9, lanePairIndex: 3 }, { teamA: 10, teamB: 12, lanePairIndex: 4 }, { teamA: 5, teamB: 4, lanePairIndex: 5 }, { teamA: 15, teamB: 13, lanePairIndex: 6 }, { teamA: 16, teamB: 3, lanePairIndex: 7 }],
            [{ teamA: 4, teamB: 13, lanePairIndex: 0 }, { teamA: 15, teamB: 3, lanePairIndex: 1 }, { teamA: 11, teamB: 8, lanePairIndex: 2 }, { teamA: 1, teamB: 14, lanePairIndex: 3 }, { teamA: 2, teamB: 16, lanePairIndex: 4 }, { teamA: 12, teamB: 9, lanePairIndex: 5 }, { teamA: 7, teamB: 5, lanePairIndex: 6 }, { teamA: 6, teamB: 10, lanePairIndex: 7 }],
            [{ teamA: 12, teamB: 1, lanePairIndex: 0 }, { teamA: 10, teamB: 8, lanePairIndex: 1 }, { teamA: 3, teamB: 5, lanePairIndex: 2 }, { teamA: 2, teamB: 4, lanePairIndex: 3 }, { teamA: 14, teamB: 9, lanePairIndex: 4 }, { teamA: 13, teamB: 16, lanePairIndex: 5 }, { teamA: 11, teamB: 6, lanePairIndex: 6 }, { teamA: 7, teamB: 15, lanePairIndex: 7 }],
            [{ teamA: 11, teamB: 10, lanePairIndex: 0 }, { teamA: 13, teamB: 2, lanePairIndex: 1 }, { teamA: 16, teamB: 4, lanePairIndex: 2 }, { teamA: 5, teamB: 15, lanePairIndex: 3 }, { teamA: 7, teamB: 3, lanePairIndex: 4 }, { teamA: 8, teamB: 6, lanePairIndex: 5 }, { teamA: 9, teamB: 1, lanePairIndex: 6 }, { teamA: 14, teamB: 12, lanePairIndex: 7 }],
            [{ teamA: 2, teamB: 6, lanePairIndex: 0 }, { teamA: 4, teamB: 11, lanePairIndex: 1 }, { teamA: 9, teamB: 15, lanePairIndex: 2 }, { teamA: 3, teamB: 12, lanePairIndex: 3 }, { teamA: 13, teamB: 8, lanePairIndex: 4 }, { teamA: 14, teamB: 7, lanePairIndex: 5 }, { teamA: 16, teamB: 10, lanePairIndex: 6 }, { teamA: 5, teamB: 1, lanePairIndex: 7 }],
            [{ teamA: 5, teamB: 9, lanePairIndex: 0 }, { teamA: 12, teamB: 7, lanePairIndex: 1 }, { teamA: 6, teamB: 13, lanePairIndex: 2 }, { teamA: 16, teamB: 11, lanePairIndex: 3 }, { teamA: 1, teamB: 15, lanePairIndex: 4 }, { teamA: 4, teamB: 10, lanePairIndex: 5 }, { teamA: 14, teamB: 3, lanePairIndex: 6 }, { teamA: 8, teamB: 2, lanePairIndex: 7 }],
            [{ teamA: 14, teamB: 15, lanePairIndex: 0 }, { teamA: 16, teamB: 6, lanePairIndex: 1 }, { teamA: 1, teamB: 7, lanePairIndex: 2 }, { teamA: 13, teamB: 10, lanePairIndex: 3 }, { teamA: 12, teamB: 5, lanePairIndex: 4 }, { teamA: 2, teamB: 11, lanePairIndex: 5 }, { teamA: 8, teamB: 4, lanePairIndex: 6 }, { teamA: 3, teamB: 9, lanePairIndex: 7 }],
            [{ teamA: 16, teamB: 8, lanePairIndex: 0 }, { teamA: 14, teamB: 5, lanePairIndex: 1 }, { teamA: 10, teamB: 2, lanePairIndex: 2 }, { teamA: 9, teamB: 7, lanePairIndex: 3 }, { teamA: 4, teamB: 6, lanePairIndex: 4 }, { teamA: 3, teamB: 1, lanePairIndex: 5 }, { teamA: 12, teamB: 15, lanePairIndex: 6 }, { teamA: 11, teamB: 13, lanePairIndex: 7 }],
        ]
    },
    18: {
        teamCount: 18,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }, { teamA: 9, teamB: 10, lanePairIndex: 4 }, { teamA: 11, teamB: 12, lanePairIndex: 5 }, { teamA: 13, teamB: 14, lanePairIndex: 6 }, { teamA: 15, teamB: 16, lanePairIndex: 7 }, { teamA: 17, teamB: 18, lanePairIndex: 8 }],
            [{ teamA: 3, teamB: 6, lanePairIndex: 0 }, { teamA: 5, teamB: 1, lanePairIndex: 1 }, { teamA: 2, teamB: 4, lanePairIndex: 2 }, { teamA: 11, teamB: 10, lanePairIndex: 3 }, { teamA: 7, teamB: 12, lanePairIndex: 4 }, { teamA: 9, teamB: 8, lanePairIndex: 5 }, { teamA: 18, teamB: 16, lanePairIndex: 6 }, { teamA: 13, teamB: 17, lanePairIndex: 7 }, { teamA: 14, teamB: 15, lanePairIndex: 8 }],
            [{ teamA: 5, teamB: 4, lanePairIndex: 0 }, { teamA: 2, teamB: 6, lanePairIndex: 1 }, { teamA: 3, teamB: 1, lanePairIndex: 2 }, { teamA: 9, teamB: 12, lanePairIndex: 3 }, { teamA: 11, teamB: 8, lanePairIndex: 4 }, { teamA: 7, teamB: 10, lanePairIndex: 5 }, { teamA: 15, teamB: 17, lanePairIndex: 6 }, { teamA: 18, teamB: 14, lanePairIndex: 7 }, { teamA: 16, teamB: 13, lanePairIndex: 8 }],
            [{ teamA: 7, teamB: 9, lanePairIndex: 0 }, { teamA: 13, teamB: 15, lanePairIndex: 1 }, { teamA: 18, teamB: 11, lanePairIndex: 2 }, { teamA: 16, teamB: 14, lanePairIndex: 3 }, { teamA: 3, teamB: 2, lanePairIndex: 4 }, { teamA: 17, teamB: 5, lanePairIndex: 5 }, { teamA: 1, teamB: 4, lanePairIndex: 6 }, { teamA: 8, teamB: 10, lanePairIndex: 7 }, { teamA: 12, teamB: 6, lanePairIndex: 8 }],
            [{ teamA: 14, teamB: 1, lanePairIndex: 0 }, { teamA: 4, teamB: 16, lanePairIndex: 1 }, { teamA: 6, teamB: 17, lanePairIndex: 2 }, { teamA: 8, teamB: 13, lanePairIndex: 3 }, { teamA: 10, teamB: 15, lanePairIndex: 4 }, { teamA: 12, teamB: 18, lanePairIndex: 5 }, { teamA: 7, teamB: 2, lanePairIndex: 6 }, { teamA: 9, teamB: 3, lanePairIndex: 7 }, { teamA: 5, teamB: 11, lanePairIndex: 8 }],
            [{ teamA: 6, teamB: 16, lanePairIndex: 0 }, { teamA: 1, teamB: 17, lanePairIndex: 1 }, { teamA: 4, teamB: 14, lanePairIndex: 2 }, { teamA: 10, teamB: 18, lanePairIndex: 3 }, { teamA: 12, teamB: 13, lanePairIndex: 4 }, { teamA: 8, teamB: 15, lanePairIndex: 5 }, { teamA: 9, teamB: 5, lanePairIndex: 6 }, { teamA: 11, teamB: 2, lanePairIndex: 7 }, { teamA: 3, teamB: 7, lanePairIndex: 8 }],
            [{ teamA: 4, teamB: 17, lanePairIndex: 0 }, { teamA: 6, teamB: 14, lanePairIndex: 1 }, { teamA: 1, teamB: 16, lanePairIndex: 2 }, { teamA: 12, teamB: 15, lanePairIndex: 3 }, { teamA: 8, teamB: 18, lanePairIndex: 4 }, { teamA: 10, teamB: 13, lanePairIndex: 5 }, { teamA: 11, teamB: 3, lanePairIndex: 6 }, { teamA: 7, teamB: 5, lanePairIndex: 7 }, { teamA: 2, teamB: 9, lanePairIndex: 8 }],
            [{ teamA: 13, teamB: 7, lanePairIndex: 0 }, { teamA: 9, teamB: 11, lanePairIndex: 1 }, { teamA: 15, teamB: 18, lanePairIndex: 2 }, { teamA: 14, teamB: 2, lanePairIndex: 3 }, { teamA: 17, teamB: 16, lanePairIndex: 4 }, { teamA: 5, teamB: 3, lanePairIndex: 5 }, { teamA: 8, teamB: 1, lanePairIndex: 6 }, { teamA: 4, teamB: 6, lanePairIndex: 7 }, { teamA: 10, teamB: 12, lanePairIndex: 8 }],
            [{ teamA: 2, teamB: 8, lanePairIndex: 0 }, { teamA: 10, teamB: 3, lanePairIndex: 1 }, { teamA: 12, teamB: 5, lanePairIndex: 2 }, { teamA: 13, teamB: 1, lanePairIndex: 3 }, { teamA: 15, teamB: 4, lanePairIndex: 4 }, { teamA: 18, teamB: 6, lanePairIndex: 5 }, { teamA: 14, teamB: 7, lanePairIndex: 6 }, { teamA: 16, teamB: 9, lanePairIndex: 7 }, { teamA: 11, teamB: 17, lanePairIndex: 8 }],
            [{ teamA: 12, teamB: 3, lanePairIndex: 0 }, { teamA: 8, teamB: 5, lanePairIndex: 1 }, { teamA: 10, teamB: 2, lanePairIndex: 2 }, { teamA: 18, teamB: 4, lanePairIndex: 3 }, { teamA: 13, teamB: 6, lanePairIndex: 4 }, { teamA: 15, teamB: 1, lanePairIndex: 5 }, { teamA: 17, teamB: 9, lanePairIndex: 6 }, { teamA: 14, teamB: 11, lanePairIndex: 7 }, { teamA: 7, teamB: 16, lanePairIndex: 8 }],
            [{ teamA: 10, teamB: 5, lanePairIndex: 0 }, { teamA: 12, teamB: 2, lanePairIndex: 1 }, { teamA: 8, teamB: 3, lanePairIndex: 2 }, { teamA: 15, teamB: 6, lanePairIndex: 3 }, { teamA: 18, teamB: 1, lanePairIndex: 4 }, { teamA: 13, teamB: 4, lanePairIndex: 5 }, { teamA: 16, teamB: 11, lanePairIndex: 6 }, { teamA: 17, teamB: 7, lanePairIndex: 7 }, { teamA: 9, teamB: 14, lanePairIndex: 8 }],
            [{ teamA: 18, teamB: 13, lanePairIndex: 0 }, { teamA: 15, teamB: 9, lanePairIndex: 1 }, { teamA: 11, teamB: 7, lanePairIndex: 2 }, { teamA: 2, teamB: 5, lanePairIndex: 3 }, { teamA: 16, teamB: 3, lanePairIndex: 4 }, { teamA: 14, teamB: 17, lanePairIndex: 5 }, { teamA: 12, teamB: 8, lanePairIndex: 6 }, { teamA: 10, teamB: 4, lanePairIndex: 7 }, { teamA: 6, teamB: 1, lanePairIndex: 8 }],
            [{ teamA: 8, teamB: 14, lanePairIndex: 0 }, { teamA: 16, teamB: 10, lanePairIndex: 1 }, { teamA: 17, teamB: 12, lanePairIndex: 2 }, { teamA: 1, teamB: 9, lanePairIndex: 3 }, { teamA: 4, teamB: 11, lanePairIndex: 4 }, { teamA: 6, teamB: 7, lanePairIndex: 5 }, { teamA: 2, teamB: 18, lanePairIndex: 6 }, { teamA: 3, teamB: 13, lanePairIndex: 7 }, { teamA: 15, teamB: 5, lanePairIndex: 8 }],
            [{ teamA: 16, teamB: 12, lanePairIndex: 0 }, { teamA: 17, teamB: 8, lanePairIndex: 1 }, { teamA: 14, teamB: 10, lanePairIndex: 2 }, { teamA: 4, teamB: 7, lanePairIndex: 3 }, { teamA: 6, teamB: 9, lanePairIndex: 4 }, { teamA: 1, teamB: 11, lanePairIndex: 5 }, { teamA: 3, teamB: 15, lanePairIndex: 6 }, { teamA: 5, teamB: 18, lanePairIndex: 7 }, { teamA: 13, teamB: 2, lanePairIndex: 8 }],
            [{ teamA: 17, teamB: 10, lanePairIndex: 0 }, { teamA: 14, teamB: 12, lanePairIndex: 1 }, { teamA: 16, teamB: 8, lanePairIndex: 2 }, { teamA: 6, teamB: 11, lanePairIndex: 3 }, { teamA: 1, teamB: 7, lanePairIndex: 4 }, { teamA: 4, teamB: 9, lanePairIndex: 5 }, { teamA: 5, teamB: 13, lanePairIndex: 6 }, { teamA: 2, teamB: 15, lanePairIndex: 7 }, { teamA: 18, teamB: 3, lanePairIndex: 8 }],
            [{ teamA: 11, teamB: 15, lanePairIndex: 0 }, { teamA: 7, teamB: 18, lanePairIndex: 1 }, { teamA: 9, teamB: 13, lanePairIndex: 2 }, { teamA: 3, teamB: 17, lanePairIndex: 3 }, { teamA: 5, teamB: 14, lanePairIndex: 4 }, { teamA: 2, teamB: 16, lanePairIndex: 5 }, { teamA: 6, teamB: 10, lanePairIndex: 6 }, { teamA: 1, teamB: 12, lanePairIndex: 7 }, { teamA: 4, teamB: 8, lanePairIndex: 8 }],
            [{ teamA: 9, teamB: 18, lanePairIndex: 0 }, { teamA: 11, teamB: 13, lanePairIndex: 1 }, { teamA: 7, teamB: 15, lanePairIndex: 2 }, { teamA: 5, teamB: 16, lanePairIndex: 3 }, { teamA: 2, teamB: 17, lanePairIndex: 4 }, { teamA: 3, teamB: 14, lanePairIndex: 5 }, { teamA: 4, teamB: 12, lanePairIndex: 6 }, { teamA: 6, teamB: 8, lanePairIndex: 7 }, { teamA: 1, teamB: 10, lanePairIndex: 8 }],
        ]
    },
    20: {
        teamCount: 20,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }, { teamA: 9, teamB: 10, lanePairIndex: 4 }, { teamA: 11, teamB: 12, lanePairIndex: 5 }, { teamA: 13, teamB: 14, lanePairIndex: 6 }, { teamA: 15, teamB: 16, lanePairIndex: 7 }, { teamA: 17, teamB: 18, lanePairIndex: 8 }, { teamA: 19, teamB: 20, lanePairIndex: 9 }],
            [{ teamA: 3, teamB: 11, lanePairIndex: 0 }, { teamA: 2, teamB: 13, lanePairIndex: 1 }, { teamA: 9, teamB: 18, lanePairIndex: 2 }, { teamA: 17, teamB: 12, lanePairIndex: 3 }, { teamA: 5, teamB: 15, lanePairIndex: 4 }, { teamA: 8, teamB: 1, lanePairIndex: 5 }, { teamA: 4, teamB: 19, lanePairIndex: 6 }, { teamA: 20, teamB: 10, lanePairIndex: 7 }, { teamA: 7, teamB: 6, lanePairIndex: 8 }, { teamA: 16, teamB: 14, lanePairIndex: 9 }],
            [{ teamA: 8, teamB: 13, lanePairIndex: 0 }, { teamA: 11, teamB: 19, lanePairIndex: 1 }, { teamA: 15, teamB: 7, lanePairIndex: 2 }, { teamA: 10, teamB: 6, lanePairIndex: 3 }, { teamA: 20, teamB: 18, lanePairIndex: 4 }, { teamA: 3, teamB: 17, lanePairIndex: 5 }, { teamA: 2, teamB: 16, lanePairIndex: 6 }, { teamA: 14, teamB: 5, lanePairIndex: 7 }, { teamA: 9, teamB: 12, lanePairIndex: 8 }, { teamA: 1, teamB: 4, lanePairIndex: 9 }],
            [{ teamA: 17, teamB: 19, lanePairIndex: 0 }, { teamA: 16, teamB: 8, lanePairIndex: 1 }, { teamA: 20, teamB: 12, lanePairIndex: 2 }, { teamA: 3, teamB: 9, lanePairIndex: 3 }, { teamA: 7, teamB: 14, lanePairIndex: 4 }, { teamA: 13, teamB: 6, lanePairIndex: 5 }, { teamA: 10, teamB: 11, lanePairIndex: 6 }, { teamA: 4, teamB: 18, lanePairIndex: 7 }, { teamA: 1, teamB: 15, lanePairIndex: 8 }, { teamA: 2, teamB: 5, lanePairIndex: 9 }],
            [{ teamA: 16, teamB: 6, lanePairIndex: 0 }, { teamA: 10, teamB: 17, lanePairIndex: 1 }, { teamA: 1, teamB: 14, lanePairIndex: 2 }, { teamA: 15, teamB: 13, lanePairIndex: 3 }, { teamA: 4, teamB: 12, lanePairIndex: 4 }, { teamA: 19, teamB: 9, lanePairIndex: 5 }, { teamA: 5, teamB: 8, lanePairIndex: 6 }, { teamA: 7, teamB: 2, lanePairIndex: 7 }, { teamA: 3, teamB: 20, lanePairIndex: 8 }, { teamA: 18, teamB: 11, lanePairIndex: 9 }],
            [{ teamA: 10, teamB: 15, lanePairIndex: 0 }, { teamA: 9, teamB: 5, lanePairIndex: 1 }, { teamA: 3, teamB: 2, lanePairIndex: 2 }, { teamA: 14, teamB: 19, lanePairIndex: 3 }, { teamA: 1, teamB: 11, lanePairIndex: 4 }, { teamA: 20, teamB: 16, lanePairIndex: 5 }, { teamA: 18, teamB: 6, lanePairIndex: 6 }, { teamA: 8, teamB: 12, lanePairIndex: 7 }, { teamA: 13, teamB: 4, lanePairIndex: 8 }, { teamA: 17, teamB: 7, lanePairIndex: 9 }],
            [{ teamA: 20, teamB: 5, lanePairIndex: 0 }, { teamA: 15, teamB: 18, lanePairIndex: 1 }, { teamA: 11, teamB: 13, lanePairIndex: 2 }, { teamA: 16, teamB: 4, lanePairIndex: 3 }, { teamA: 3, teamB: 8, lanePairIndex: 4 }, { teamA: 14, teamB: 10, lanePairIndex: 5 }, { teamA: 7, teamB: 9, lanePairIndex: 6 }, { teamA: 1, teamB: 17, lanePairIndex: 7 }, { teamA: 19, teamB: 2, lanePairIndex: 8 }, { teamA: 6, teamB: 12, lanePairIndex: 9 }],
            [{ teamA: 14, teamB: 18, lanePairIndex: 0 }, { teamA: 20, teamB: 7, lanePairIndex: 1 }, { teamA: 8, teamB: 19, lanePairIndex: 2 }, { teamA: 2, teamB: 10, lanePairIndex: 3 }, { teamA: 17, teamB: 13, lanePairIndex: 4 }, { teamA: 5, teamB: 4, lanePairIndex: 5 }, { teamA: 15, teamB: 12, lanePairIndex: 6 }, { teamA: 3, teamB: 6, lanePairIndex: 7 }, { teamA: 11, teamB: 16, lanePairIndex: 8 }, { teamA: 9, teamB: 1, lanePairIndex: 9 }],
            [{ teamA: 7, teamB: 4, lanePairIndex: 0 }, { teamA: 12, teamB: 14, lanePairIndex: 1 }, { teamA: 16, teamB: 17, lanePairIndex: 2 }, { teamA: 11, teamB: 5, lanePairIndex: 3 }, { teamA: 6, teamB: 19, lanePairIndex: 4 }, { teamA: 2, teamB: 18, lanePairIndex: 5 }, { teamA: 20, teamB: 1, lanePairIndex: 6 }, { teamA: 13, teamB: 9, lanePairIndex: 7 }, { teamA: 8, teamB: 10, lanePairIndex: 8 }, { teamA: 3, teamB: 15, lanePairIndex: 9 }],
            [{ teamA: 2, teamB: 12, lanePairIndex: 0 }, { teamA: 1, teamB: 6, lanePairIndex: 1 }, { teamA: 10, teamB: 4, lanePairIndex: 2 }, { teamA: 13, teamB: 20, lanePairIndex: 3 }, { teamA: 16, teamB: 9, lanePairIndex: 4 }, { teamA: 7, teamB: 11, lanePairIndex: 5 }, { teamA: 17, teamB: 5, lanePairIndex: 6 }, { teamA: 19, teamB: 15, lanePairIndex: 7 }, { teamA: 14, teamB: 3, lanePairIndex: 8 }, { teamA: 8, teamB: 18, lanePairIndex: 9 }],
            [{ teamA: 5, teamB: 16, lanePairIndex: 0 }, { teamA: 7, teamB: 3, lanePairIndex: 1 }, { teamA: 2, teamB: 11, lanePairIndex: 2 }, { teamA: 6, teamB: 17, lanePairIndex: 3 }, { teamA: 15, teamB: 20, lanePairIndex: 4 }, { teamA: 9, teamB: 14, lanePairIndex: 5 }, { teamA: 8, teamB: 4, lanePairIndex: 6 }, { teamA: 10, teamB: 1, lanePairIndex: 7 }, { teamA: 18, teamB: 19, lanePairIndex: 8 }, { teamA: 12, teamB: 13, lanePairIndex: 9 }],
            [{ teamA: 15, teamB: 14, lanePairIndex: 0 }, { teamA: 4, teamB: 9, lanePairIndex: 1 }, { teamA: 18, teamB: 5, lanePairIndex: 2 }, { teamA: 12, teamB: 7, lanePairIndex: 3 }, { teamA: 11, teamB: 6, lanePairIndex: 4 }, { teamA: 17, teamB: 8, lanePairIndex: 5 }, { teamA: 19, teamB: 13, lanePairIndex: 6 }, { teamA: 2, teamB: 20, lanePairIndex: 7 }, { teamA: 16, teamB: 1, lanePairIndex: 8 }, { teamA: 10, teamB: 3, lanePairIndex: 9 }],
            [{ teamA: 6, teamB: 8, lanePairIndex: 0 }, { teamA: 17, teamB: 2, lanePairIndex: 1 }, { teamA: 7, teamB: 1, lanePairIndex: 2 }, { teamA: 20, teamB: 14, lanePairIndex: 3 }, { teamA: 18, teamB: 3, lanePairIndex: 4 }, { teamA: 4, teamB: 15, lanePairIndex: 5 }, { teamA: 16, teamB: 10, lanePairIndex: 6 }, { teamA: 12, teamB: 19, lanePairIndex: 7 }, { teamA: 5, teamB: 13, lanePairIndex: 8 }, { teamA: 11, teamB: 9, lanePairIndex: 9 }],
            [{ teamA: 9, teamB: 20, lanePairIndex: 0 }, { teamA: 13, teamB: 1, lanePairIndex: 1 }, { teamA: 17, teamB: 15, lanePairIndex: 2 }, { teamA: 8, teamB: 11, lanePairIndex: 3 }, { teamA: 14, teamB: 4, lanePairIndex: 4 }, { teamA: 6, teamB: 2, lanePairIndex: 5 }, { teamA: 12, teamB: 18, lanePairIndex: 6 }, { teamA: 16, teamB: 3, lanePairIndex: 7 }, { teamA: 10, teamB: 7, lanePairIndex: 8 }, { teamA: 5, teamB: 19, lanePairIndex: 9 }],
            [{ teamA: 11, teamB: 17, lanePairIndex: 0 }, { teamA: 5, teamB: 12, lanePairIndex: 1 }, { teamA: 4, teamB: 20, lanePairIndex: 2 }, { teamA: 9, teamB: 15, lanePairIndex: 3 }, { teamA: 8, teamB: 2, lanePairIndex: 4 }, { teamA: 10, teamB: 19, lanePairIndex: 5 }, { teamA: 1, teamB: 3, lanePairIndex: 6 }, { teamA: 18, teamB: 13, lanePairIndex: 7 }, { teamA: 6, teamB: 14, lanePairIndex: 8 }, { teamA: 7, teamB: 16, lanePairIndex: 9 }],
            [{ teamA: 13, teamB: 3, lanePairIndex: 0 }, { teamA: 8, teamB: 20, lanePairIndex: 1 }, { teamA: 12, teamB: 16, lanePairIndex: 2 }, { teamA: 19, teamB: 1, lanePairIndex: 3 }, { teamA: 10, teamB: 5, lanePairIndex: 4 }, { teamA: 18, teamB: 7, lanePairIndex: 5 }, { teamA: 11, teamB: 15, lanePairIndex: 6 }, { teamA: 17, teamB: 14, lanePairIndex: 7 }, { teamA: 2, teamB: 9, lanePairIndex: 8 }, { teamA: 4, teamB: 6, lanePairIndex: 9 }],
            [{ teamA: 12, teamB: 10, lanePairIndex: 0 }, { teamA: 14, teamB: 11, lanePairIndex: 1 }, { teamA: 19, teamB: 3, lanePairIndex: 2 }, { teamA: 18, teamB: 16, lanePairIndex: 3 }, { teamA: 13, teamB: 7, lanePairIndex: 4 }, { teamA: 1, teamB: 5, lanePairIndex: 5 }, { teamA: 6, teamB: 20, lanePairIndex: 6 }, { teamA: 9, teamB: 8, lanePairIndex: 7 }, { teamA: 4, teamB: 17, lanePairIndex: 8 }, { teamA: 15, teamB: 2, lanePairIndex: 9 }],
            [{ teamA: 19, teamB: 7, lanePairIndex: 0 }, { teamA: 18, teamB: 10, lanePairIndex: 1 }, { teamA: 6, teamB: 9, lanePairIndex: 2 }, { teamA: 5, teamB: 3, lanePairIndex: 3 }, { teamA: 12, teamB: 1, lanePairIndex: 4 }, { teamA: 16, teamB: 13, lanePairIndex: 5 }, { teamA: 14, teamB: 2, lanePairIndex: 6 }, { teamA: 11, teamB: 4, lanePairIndex: 7 }, { teamA: 15, teamB: 8, lanePairIndex: 8 }, { teamA: 20, teamB: 17, lanePairIndex: 9 }],
            [{ teamA: 18, teamB: 1, lanePairIndex: 0 }, { teamA: 6, teamB: 15, lanePairIndex: 1 }, { teamA: 13, teamB: 10, lanePairIndex: 2 }, { teamA: 4, teamB: 2, lanePairIndex: 3 }, { teamA: 19, teamB: 16, lanePairIndex: 4 }, { teamA: 12, teamB: 3, lanePairIndex: 5 }, { teamA: 9, teamB: 17, lanePairIndex: 6 }, { teamA: 5, teamB: 7, lanePairIndex: 7 }, { teamA: 20, teamB: 11, lanePairIndex: 8 }, { teamA: 14, teamB: 8, lanePairIndex: 9 }],
        ]
    },
    22: {
        teamCount: 22,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }, { teamA: 9, teamB: 10, lanePairIndex: 4 }, { teamA: 11, teamB: 12, lanePairIndex: 5 }, { teamA: 13, teamB: 14, lanePairIndex: 6 }, { teamA: 15, teamB: 16, lanePairIndex: 7 }, { teamA: 17, teamB: 18, lanePairIndex: 8 }, { teamA: 19, teamB: 20, lanePairIndex: 9 }, { teamA: 21, teamB: 22, lanePairIndex: 10 }],
            [{ teamA: 20, teamB: 5, lanePairIndex: 0 }, { teamA: 21, teamB: 15, lanePairIndex: 1 }, { teamA: 2, teamB: 3, lanePairIndex: 2 }, { teamA: 9, teamB: 22, lanePairIndex: 3 }, { teamA: 11, teamB: 8, lanePairIndex: 4 }, { teamA: 13, teamB: 10, lanePairIndex: 5 }, { teamA: 18, teamB: 7, lanePairIndex: 6 }, { teamA: 17, teamB: 19, lanePairIndex: 7 }, { teamA: 14, teamB: 6, lanePairIndex: 8 }, { teamA: 16, teamB: 1, lanePairIndex: 9 }, { teamA: 4, teamB: 12, lanePairIndex: 10 }],
            [{ teamA: 3, teamB: 16, lanePairIndex: 0 }, { teamA: 19, teamB: 7, lanePairIndex: 1 }, { teamA: 20, teamB: 14, lanePairIndex: 2 }, { teamA: 18, teamB: 11, lanePairIndex: 3 }, { teamA: 13, teamB: 22, lanePairIndex: 4 }, { teamA: 8, teamB: 4, lanePairIndex: 5 }, { teamA: 9, teamB: 15, lanePairIndex: 6 }, { teamA: 21, teamB: 1, lanePairIndex: 7 }, { teamA: 2, teamB: 12, lanePairIndex: 8 }, { teamA: 5, teamB: 17, lanePairIndex: 9 }, { teamA: 6, teamB: 10, lanePairIndex: 10 }],
            [{ teamA: 9, teamB: 8, lanePairIndex: 0 }, { teamA: 4, teamB: 14, lanePairIndex: 1 }, { teamA: 13, teamB: 12, lanePairIndex: 2 }, { teamA: 2, teamB: 5, lanePairIndex: 3 }, { teamA: 20, teamB: 1, lanePairIndex: 4 }, { teamA: 16, teamB: 19, lanePairIndex: 5 }, { teamA: 3, teamB: 6, lanePairIndex: 6 }, { teamA: 7, teamB: 22, lanePairIndex: 7 }, { teamA: 18, teamB: 21, lanePairIndex: 8 }, { teamA: 11, teamB: 10, lanePairIndex: 9 }, { teamA: 17, teamB: 15, lanePairIndex: 10 }],
            [{ teamA: 13, teamB: 18, lanePairIndex: 0 }, { teamA: 10, teamB: 2, lanePairIndex: 1 }, { teamA: 11, teamB: 15, lanePairIndex: 2 }, { teamA: 14, teamB: 16, lanePairIndex: 3 }, { teamA: 3, teamB: 17, lanePairIndex: 4 }, { teamA: 5, teamB: 21, lanePairIndex: 5 }, { teamA: 12, teamB: 20, lanePairIndex: 6 }, { teamA: 6, teamB: 8, lanePairIndex: 7 }, { teamA: 9, teamB: 19, lanePairIndex: 8 }, { teamA: 4, teamB: 22, lanePairIndex: 9 }, { teamA: 1, teamB: 7, lanePairIndex: 10 }],
            [{ teamA: 11, teamB: 22, lanePairIndex: 0 }, { teamA: 12, teamB: 6, lanePairIndex: 1 }, { teamA: 18, teamB: 9, lanePairIndex: 2 }, { teamA: 3, teamB: 20, lanePairIndex: 3 }, { teamA: 5, teamB: 16, lanePairIndex: 4 }, { teamA: 1, teamB: 17, lanePairIndex: 5 }, { teamA: 14, teamB: 2, lanePairIndex: 6 }, { teamA: 10, teamB: 4, lanePairIndex: 7 }, { teamA: 7, teamB: 15, lanePairIndex: 8 }, { teamA: 13, teamB: 8, lanePairIndex: 9 }, { teamA: 19, teamB: 21, lanePairIndex: 10 }],
            [{ teamA: 14, teamB: 17, lanePairIndex: 0 }, { teamA: 9, teamB: 1, lanePairIndex: 1 }, { teamA: 12, teamB: 16, lanePairIndex: 2 }, { teamA: 13, teamB: 15, lanePairIndex: 3 }, { teamA: 18, teamB: 4, lanePairIndex: 4 }, { teamA: 6, teamB: 22, lanePairIndex: 5 }, { teamA: 11, teamB: 19, lanePairIndex: 6 }, { teamA: 5, teamB: 7, lanePairIndex: 7 }, { teamA: 10, teamB: 20, lanePairIndex: 8 }, { teamA: 3, teamB: 21, lanePairIndex: 9 }, { teamA: 8, teamB: 2, lanePairIndex: 10 }],
            [{ teamA: 21, teamB: 12, lanePairIndex: 0 }, { teamA: 5, teamB: 11, lanePairIndex: 1 }, { teamA: 17, teamB: 10, lanePairIndex: 2 }, { teamA: 19, teamB: 4, lanePairIndex: 3 }, { teamA: 15, teamB: 6, lanePairIndex: 4 }, { teamA: 18, teamB: 2, lanePairIndex: 5 }, { teamA: 1, teamB: 13, lanePairIndex: 6 }, { teamA: 9, teamB: 3, lanePairIndex: 7 }, { teamA: 16, teamB: 8, lanePairIndex: 8 }, { teamA: 7, teamB: 14, lanePairIndex: 9 }, { teamA: 22, teamB: 20, lanePairIndex: 10 }],
            [{ teamA: 15, teamB: 4, lanePairIndex: 0 }, { teamA: 20, teamB: 8, lanePairIndex: 1 }, { teamA: 19, teamB: 13, lanePairIndex: 2 }, { teamA: 17, teamB: 12, lanePairIndex: 3 }, { teamA: 14, teamB: 21, lanePairIndex: 4 }, { teamA: 7, teamB: 3, lanePairIndex: 5 }, { teamA: 16, teamB: 10, lanePairIndex: 6 }, { teamA: 22, teamB: 2, lanePairIndex: 7 }, { teamA: 1, teamB: 11, lanePairIndex: 8 }, { teamA: 18, teamB: 6, lanePairIndex: 9 }, { teamA: 9, teamB: 5, lanePairIndex: 10 }],
            [{ teamA: 6, teamB: 19, lanePairIndex: 0 }, { teamA: 16, teamB: 22, lanePairIndex: 1 }, { teamA: 4, teamB: 1, lanePairIndex: 2 }, { teamA: 21, teamB: 10, lanePairIndex: 3 }, { teamA: 7, teamB: 12, lanePairIndex: 4 }, { teamA: 9, teamB: 14, lanePairIndex: 5 }, { teamA: 17, teamB: 8, lanePairIndex: 6 }, { teamA: 20, teamB: 18, lanePairIndex: 7 }, { teamA: 5, teamB: 13, lanePairIndex: 8 }, { teamA: 2, teamB: 15, lanePairIndex: 9 }, { teamA: 11, teamB: 3, lanePairIndex: 10 }],
            [{ teamA: 12, teamB: 10, lanePairIndex: 0 }, { teamA: 17, teamB: 13, lanePairIndex: 1 }, { teamA: 6, teamB: 20, lanePairIndex: 2 }, { teamA: 8, teamB: 14, lanePairIndex: 3 }, { teamA: 2, teamB: 19, lanePairIndex: 4 }, { teamA: 21, teamB: 11, lanePairIndex: 5 }, { teamA: 5, teamB: 18, lanePairIndex: 6 }, { teamA: 1, teamB: 15, lanePairIndex: 7 }, { teamA: 3, teamB: 22, lanePairIndex: 8 }, { teamA: 9, teamB: 7, lanePairIndex: 9 }, { teamA: 16, teamB: 4, lanePairIndex: 10 }],
            [{ teamA: 17, teamB: 9, lanePairIndex: 0 }, { teamA: 18, teamB: 19, lanePairIndex: 1 }, { teamA: 16, teamB: 2, lanePairIndex: 2 }, { teamA: 1, teamB: 6, lanePairIndex: 3 }, { teamA: 4, teamB: 13, lanePairIndex: 4 }, { teamA: 3, teamB: 5, lanePairIndex: 5 }, { teamA: 20, teamB: 21, lanePairIndex: 6 }, { teamA: 14, teamB: 10, lanePairIndex: 7 }, { teamA: 11, teamB: 7, lanePairIndex: 8 }, { teamA: 22, teamB: 12, lanePairIndex: 9 }, { teamA: 15, teamB: 8, lanePairIndex: 10 }],
            [{ teamA: 7, teamB: 13, lanePairIndex: 0 }, { teamA: 8, teamB: 12, lanePairIndex: 1 }, { teamA: 9, teamB: 21, lanePairIndex: 2 }, { teamA: 16, teamB: 17, lanePairIndex: 3 }, { teamA: 22, teamB: 18, lanePairIndex: 4 }, { teamA: 15, teamB: 20, lanePairIndex: 5 }, { teamA: 6, teamB: 11, lanePairIndex: 6 }, { teamA: 19, teamB: 5, lanePairIndex: 7 }, { teamA: 2, teamB: 4, lanePairIndex: 8 }, { teamA: 10, teamB: 3, lanePairIndex: 9 }, { teamA: 14, teamB: 1, lanePairIndex: 10 }],
            [{ teamA: 22, teamB: 14, lanePairIndex: 0 }, { teamA: 6, teamB: 21, lanePairIndex: 1 }, { teamA: 1, teamB: 8, lanePairIndex: 2 }, { teamA: 20, teamB: 7, lanePairIndex: 3 }, { teamA: 10, teamB: 15, lanePairIndex: 4 }, { teamA: 4, teamB: 9, lanePairIndex: 5 }, { teamA: 19, teamB: 3, lanePairIndex: 6 }, { teamA: 2, teamB: 13, lanePairIndex: 7 }, { teamA: 12, teamB: 5, lanePairIndex: 8 }, { teamA: 17, teamB: 11, lanePairIndex: 9 }, { teamA: 18, teamB: 16, lanePairIndex: 10 }],
            [{ teamA: 18, teamB: 1, lanePairIndex: 0 }, { teamA: 11, teamB: 9, lanePairIndex: 1 }, { teamA: 10, teamB: 5, lanePairIndex: 2 }, { teamA: 15, teamB: 3, lanePairIndex: 3 }, { teamA: 21, teamB: 2, lanePairIndex: 4 }, { teamA: 19, teamB: 8, lanePairIndex: 5 }, { teamA: 7, teamB: 4, lanePairIndex: 6 }, { teamA: 12, teamB: 14, lanePairIndex: 7 }, { teamA: 22, teamB: 17, lanePairIndex: 8 }, { teamA: 6, teamB: 16, lanePairIndex: 9 }, { teamA: 20, teamB: 13, lanePairIndex: 10 }],
            [{ teamA: 16, teamB: 21, lanePairIndex: 0 }, { teamA: 22, teamB: 5, lanePairIndex: 1 }, { teamA: 14, teamB: 11, lanePairIndex: 2 }, { teamA: 6, teamB: 13, lanePairIndex: 3 }, { teamA: 1, teamB: 3, lanePairIndex: 4 }, { teamA: 2, teamB: 7, lanePairIndex: 5 }, { teamA: 15, teamB: 12, lanePairIndex: 6 }, { teamA: 4, teamB: 17, lanePairIndex: 7 }, { teamA: 20, teamB: 9, lanePairIndex: 8 }, { teamA: 8, teamB: 18, lanePairIndex: 9 }, { teamA: 10, teamB: 19, lanePairIndex: 10 }],
            [{ teamA: 2, teamB: 6, lanePairIndex: 0 }, { teamA: 15, teamB: 18, lanePairIndex: 1 }, { teamA: 7, teamB: 17, lanePairIndex: 2 }, { teamA: 4, teamB: 21, lanePairIndex: 3 }, { teamA: 8, teamB: 5, lanePairIndex: 4 }, { teamA: 20, teamB: 16, lanePairIndex: 5 }, { teamA: 10, teamB: 22, lanePairIndex: 6 }, { teamA: 13, teamB: 11, lanePairIndex: 7 }, { teamA: 19, teamB: 1, lanePairIndex: 8 }, { teamA: 12, teamB: 9, lanePairIndex: 9 }, { teamA: 3, teamB: 14, lanePairIndex: 10 }],
            [{ teamA: 10, teamB: 7, lanePairIndex: 0 }, { teamA: 2, teamB: 20, lanePairIndex: 1 }, { teamA: 8, teamB: 22, lanePairIndex: 2 }, { teamA: 5, teamB: 1, lanePairIndex: 3 }, { teamA: 16, teamB: 11, lanePairIndex: 4 }, { teamA: 14, teamB: 18, lanePairIndex: 5 }, { teamA: 21, teamB: 17, lanePairIndex: 6 }, { teamA: 3, teamB: 12, lanePairIndex: 7 }, { teamA: 6, teamB: 4, lanePairIndex: 8 }, { teamA: 15, teamB: 19, lanePairIndex: 9 }, { teamA: 13, teamB: 9, lanePairIndex: 10 }],
            [{ teamA: 4, teamB: 11, lanePairIndex: 0 }, { teamA: 1, teamB: 10, lanePairIndex: 1 }, { teamA: 3, teamB: 18, lanePairIndex: 2 }, { teamA: 12, teamB: 19, lanePairIndex: 3 }, { teamA: 17, teamB: 20, lanePairIndex: 4 }, { teamA: 22, teamB: 15, lanePairIndex: 5 }, { teamA: 2, teamB: 9, lanePairIndex: 6 }, { teamA: 8, teamB: 21, lanePairIndex: 7 }, { teamA: 13, teamB: 16, lanePairIndex: 8 }, { teamA: 14, teamB: 5, lanePairIndex: 9 }, { teamA: 7, teamB: 6, lanePairIndex: 10 }],
            [{ teamA: 5, teamB: 15, lanePairIndex: 0 }, { teamA: 13, teamB: 3, lanePairIndex: 1 }, { teamA: 21, teamB: 7, lanePairIndex: 2 }, { teamA: 11, teamB: 2, lanePairIndex: 3 }, { teamA: 19, teamB: 14, lanePairIndex: 4 }, { teamA: 17, teamB: 6, lanePairIndex: 5 }, { teamA: 22, teamB: 1, lanePairIndex: 6 }, { teamA: 16, teamB: 9, lanePairIndex: 7 }, { teamA: 8, teamB: 10, lanePairIndex: 8 }, { teamA: 20, teamB: 4, lanePairIndex: 9 }, { teamA: 12, teamB: 18, lanePairIndex: 10 }],
            [{ teamA: 8, teamB: 3, lanePairIndex: 0 }, { teamA: 7, teamB: 16, lanePairIndex: 1 }, { teamA: 22, teamB: 19, lanePairIndex: 2 }, { teamA: 10, teamB: 18, lanePairIndex: 3 }, { teamA: 6, teamB: 9, lanePairIndex: 4 }, { teamA: 12, teamB: 1, lanePairIndex: 5 }, { teamA: 4, teamB: 5, lanePairIndex: 6 }, { teamA: 11, teamB: 20, lanePairIndex: 7 }, { teamA: 15, teamB: 14, lanePairIndex: 8 }, { teamA: 21, teamB: 13, lanePairIndex: 9 }, { teamA: 2, teamB: 17, lanePairIndex: 10 }],
        ]
    },
    24: {
        teamCount: 24,
        rounds: [
            [{ teamA: 1, teamB: 2, lanePairIndex: 0 }, { teamA: 3, teamB: 4, lanePairIndex: 1 }, { teamA: 5, teamB: 6, lanePairIndex: 2 }, { teamA: 7, teamB: 8, lanePairIndex: 3 }, { teamA: 9, teamB: 10, lanePairIndex: 4 }, { teamA: 11, teamB: 12, lanePairIndex: 5 }, { teamA: 13, teamB: 14, lanePairIndex: 6 }, { teamA: 15, teamB: 16, lanePairIndex: 7 }, { teamA: 17, teamB: 18, lanePairIndex: 8 }, { teamA: 19, teamB: 20, lanePairIndex: 9 }, { teamA: 21, teamB: 22, lanePairIndex: 10 }, { teamA: 23, teamB: 24, lanePairIndex: 11 }],
            [{ teamA: 7, teamB: 6, lanePairIndex: 0 }, { teamA: 5, teamB: 8, lanePairIndex: 1 }, { teamA: 3, teamB: 2, lanePairIndex: 2 }, { teamA: 1, teamB: 4, lanePairIndex: 3 }, { teamA: 15, teamB: 14, lanePairIndex: 4 }, { teamA: 13, teamB: 16, lanePairIndex: 5 }, { teamA: 11, teamB: 10, lanePairIndex: 6 }, { teamA: 9, teamB: 12, lanePairIndex: 7 }, { teamA: 23, teamB: 22, lanePairIndex: 8 }, { teamA: 21, teamB: 24, lanePairIndex: 9 }, { teamA: 19, teamB: 18, lanePairIndex: 10 }, { teamA: 17, teamB: 20, lanePairIndex: 11 }],
            [{ teamA: 3, teamB: 8, lanePairIndex: 0 }, { teamA: 1, teamB: 6, lanePairIndex: 1 }, { teamA: 7, teamB: 4, lanePairIndex: 2 }, { teamA: 5, teamB: 2, lanePairIndex: 3 }, { teamA: 11, teamB: 16, lanePairIndex: 4 }, { teamA: 9, teamB: 14, lanePairIndex: 5 }, { teamA: 15, teamB: 12, lanePairIndex: 6 }, { teamA: 13, teamB: 10, lanePairIndex: 7 }, { teamA: 19, teamB: 24, lanePairIndex: 8 }, { teamA: 17, teamB: 22, lanePairIndex: 9 }, { teamA: 23, teamB: 20, lanePairIndex: 10 }, { teamA: 21, teamB: 18, lanePairIndex: 11 }],
            [{ teamA: 5, teamB: 4, lanePairIndex: 0 }, { teamA: 7, teamB: 2, lanePairIndex: 1 }, { teamA: 1, teamB: 8, lanePairIndex: 2 }, { teamA: 3, teamB: 6, lanePairIndex: 3 }, { teamA: 13, teamB: 12, lanePairIndex: 4 }, { teamA: 15, teamB: 10, lanePairIndex: 5 }, { teamA: 9, teamB: 16, lanePairIndex: 6 }, { teamA: 11, teamB: 14, lanePairIndex: 7 }, { teamA: 21, teamB: 20, lanePairIndex: 8 }, { teamA: 23, teamB: 18, lanePairIndex: 9 }, { teamA: 17, teamB: 24, lanePairIndex: 10 }, { teamA: 19, teamB: 22, lanePairIndex: 11 }],
            [{ teamA: 12, teamB: 24, lanePairIndex: 0 }, { teamA: 18, teamB: 14, lanePairIndex: 1 }, { teamA: 20, teamB: 16, lanePairIndex: 2 }, { teamA: 10, teamB: 22, lanePairIndex: 3 }, { teamA: 23, teamB: 3, lanePairIndex: 4 }, { teamA: 17, teamB: 5, lanePairIndex: 5 }, { teamA: 7, teamB: 19, lanePairIndex: 6 }, { teamA: 21, teamB: 1, lanePairIndex: 7 }, { teamA: 8, teamB: 11, lanePairIndex: 8 }, { teamA: 2, teamB: 13, lanePairIndex: 9 }, { teamA: 4, teamB: 15, lanePairIndex: 10 }, { teamA: 6, teamB: 9, lanePairIndex: 11 }],
            [{ teamA: 10, teamB: 18, lanePairIndex: 0 }, { teamA: 20, teamB: 12, lanePairIndex: 1 }, { teamA: 22, teamB: 14, lanePairIndex: 2 }, { teamA: 16, teamB: 24, lanePairIndex: 3 }, { teamA: 17, teamB: 1, lanePairIndex: 4 }, { teamA: 19, teamB: 3, lanePairIndex: 5 }, { teamA: 5, teamB: 21, lanePairIndex: 6 }, { teamA: 23, teamB: 7, lanePairIndex: 7 }, { teamA: 2, teamB: 9, lanePairIndex: 8 }, { teamA: 4, teamB: 11, lanePairIndex: 9 }, { teamA: 6, teamB: 13, lanePairIndex: 10 }, { teamA: 8, teamB: 15, lanePairIndex: 11 }],
            [{ teamA: 22, teamB: 16, lanePairIndex: 0 }, { teamA: 10, teamB: 24, lanePairIndex: 1 }, { teamA: 12, teamB: 18, lanePairIndex: 2 }, { teamA: 20, teamB: 14, lanePairIndex: 3 }, { teamA: 7, teamB: 21, lanePairIndex: 4 }, { teamA: 1, teamB: 23, lanePairIndex: 5 }, { teamA: 17, teamB: 3, lanePairIndex: 6 }, { teamA: 5, teamB: 19, lanePairIndex: 7 }, { teamA: 15, teamB: 6, lanePairIndex: 8 }, { teamA: 9, teamB: 8, lanePairIndex: 9 }, { teamA: 11, teamB: 2, lanePairIndex: 10 }, { teamA: 13, teamB: 4, lanePairIndex: 11 }],
            [{ teamA: 9, teamB: 1, lanePairIndex: 0 }, { teamA: 11, teamB: 3, lanePairIndex: 1 }, { teamA: 13, teamB: 5, lanePairIndex: 2 }, { teamA: 15, teamB: 7, lanePairIndex: 3 }, { teamA: 2, teamB: 18, lanePairIndex: 4 }, { teamA: 4, teamB: 20, lanePairIndex: 5 }, { teamA: 6, teamB: 22, lanePairIndex: 6 }, { teamA: 8, teamB: 24, lanePairIndex: 7 }, { teamA: 10, teamB: 17, lanePairIndex: 8 }, { teamA: 12, teamB: 19, lanePairIndex: 9 }, { teamA: 14, teamB: 21, lanePairIndex: 10 }, { teamA: 16, teamB: 23, lanePairIndex: 11 }],
            [{ teamA: 13, teamB: 7, lanePairIndex: 0 }, { teamA: 15, teamB: 5, lanePairIndex: 1 }, { teamA: 9, teamB: 3, lanePairIndex: 2 }, { teamA: 11, teamB: 1, lanePairIndex: 3 }, { teamA: 8, teamB: 22, lanePairIndex: 4 }, { teamA: 6, teamB: 24, lanePairIndex: 5 }, { teamA: 4, teamB: 18, lanePairIndex: 6 }, { teamA: 2, teamB: 20, lanePairIndex: 7 }, { teamA: 14, teamB: 23, lanePairIndex: 8 }, { teamA: 16, teamB: 21, lanePairIndex: 9 }, { teamA: 10, teamB: 19, lanePairIndex: 10 }, { teamA: 12, teamB: 17, lanePairIndex: 11 }],
            [{ teamA: 15, teamB: 3, lanePairIndex: 0 }, { teamA: 13, teamB: 1, lanePairIndex: 1 }, { teamA: 11, teamB: 7, lanePairIndex: 2 }, { teamA: 9, teamB: 5, lanePairIndex: 3 }, { teamA: 4, teamB: 24, lanePairIndex: 4 }, { teamA: 2, teamB: 22, lanePairIndex: 5 }, { teamA: 8, teamB: 20, lanePairIndex: 6 }, { teamA: 6, teamB: 18, lanePairIndex: 7 }, { teamA: 16, teamB: 19, lanePairIndex: 8 }, { teamA: 14, teamB: 17, lanePairIndex: 9 }, { teamA: 12, teamB: 23, lanePairIndex: 10 }, { teamA: 10, teamB: 21, lanePairIndex: 11 }],
            [{ teamA: 11, teamB: 5, lanePairIndex: 0 }, { teamA: 9, teamB: 7, lanePairIndex: 1 }, { teamA: 15, teamB: 1, lanePairIndex: 2 }, { teamA: 13, teamB: 3, lanePairIndex: 3 }, { teamA: 6, teamB: 20, lanePairIndex: 4 }, { teamA: 8, teamB: 18, lanePairIndex: 5 }, { teamA: 2, teamB: 24, lanePairIndex: 6 }, { teamA: 4, teamB: 22, lanePairIndex: 7 }, { teamA: 12, teamB: 21, lanePairIndex: 8 }, { teamA: 10, teamB: 23, lanePairIndex: 9 }, { teamA: 16, teamB: 17, lanePairIndex: 10 }, { teamA: 14, teamB: 19, lanePairIndex: 11 }],
            [{ teamA: 18, teamB: 20, lanePairIndex: 0 }, { teamA: 14, teamB: 16, lanePairIndex: 1 }, { teamA: 24, teamB: 22, lanePairIndex: 2 }, { teamA: 12, teamB: 10, lanePairIndex: 3 }, { teamA: 19, teamB: 17, lanePairIndex: 4 }, { teamA: 5, teamB: 7, lanePairIndex: 5 }, { teamA: 21, teamB: 23, lanePairIndex: 6 }, { teamA: 1, teamB: 3, lanePairIndex: 7 }, { teamA: 4, teamB: 2, lanePairIndex: 8 }, { teamA: 13, teamB: 15, lanePairIndex: 9 }, { teamA: 8, teamB: 6, lanePairIndex: 10 }, { teamA: 9, teamB: 11, lanePairIndex: 11 }],
            [{ teamA: 24, teamB: 14, lanePairIndex: 0 }, { teamA: 12, teamB: 22, lanePairIndex: 1 }, { teamA: 10, teamB: 20, lanePairIndex: 2 }, { teamA: 18, teamB: 16, lanePairIndex: 3 }, { teamA: 5, teamB: 23, lanePairIndex: 4 }, { teamA: 3, teamB: 21, lanePairIndex: 5 }, { teamA: 19, teamB: 1, lanePairIndex: 6 }, { teamA: 7, teamB: 17, lanePairIndex: 7 }, { teamA: 13, teamB: 8, lanePairIndex: 8 }, { teamA: 11, teamB: 6, lanePairIndex: 9 }, { teamA: 9, teamB: 4, lanePairIndex: 10 }, { teamA: 15, teamB: 2, lanePairIndex: 11 }],
            [{ teamA: 2, teamB: 17, lanePairIndex: 0 }, { teamA: 4, teamB: 19, lanePairIndex: 1 }, { teamA: 6, teamB: 21, lanePairIndex: 2 }, { teamA: 8, teamB: 23, lanePairIndex: 3 }, { teamA: 18, teamB: 9, lanePairIndex: 4 }, { teamA: 20, teamB: 11, lanePairIndex: 5 }, { teamA: 22, teamB: 13, lanePairIndex: 6 }, { teamA: 24, teamB: 15, lanePairIndex: 7 }, { teamA: 1, teamB: 10, lanePairIndex: 8 }, { teamA: 3, teamB: 12, lanePairIndex: 9 }, { teamA: 5, teamB: 14, lanePairIndex: 10 }, { teamA: 7, teamB: 16, lanePairIndex: 11 }],
            [{ teamA: 6, teamB: 23, lanePairIndex: 0 }, { teamA: 8, teamB: 21, lanePairIndex: 1 }, { teamA: 2, teamB: 19, lanePairIndex: 2 }, { teamA: 4, teamB: 17, lanePairIndex: 3 }, { teamA: 22, teamB: 15, lanePairIndex: 4 }, { teamA: 24, teamB: 13, lanePairIndex: 5 }, { teamA: 18, teamB: 11, lanePairIndex: 6 }, { teamA: 20, teamB: 9, lanePairIndex: 7 }, { teamA: 7, teamB: 14, lanePairIndex: 8 }, { teamA: 5, teamB: 16, lanePairIndex: 9 }, { teamA: 3, teamB: 10, lanePairIndex: 10 }, { teamA: 1, teamB: 12, lanePairIndex: 11 }],
            [{ teamA: 8, teamB: 19, lanePairIndex: 0 }, { teamA: 6, teamB: 17, lanePairIndex: 1 }, { teamA: 4, teamB: 23, lanePairIndex: 2 }, { teamA: 2, teamB: 21, lanePairIndex: 3 }, { teamA: 24, teamB: 11, lanePairIndex: 4 }, { teamA: 22, teamB: 9, lanePairIndex: 5 }, { teamA: 20, teamB: 15, lanePairIndex: 6 }, { teamA: 18, teamB: 13, lanePairIndex: 7 }, { teamA: 3, teamB: 16, lanePairIndex: 8 }, { teamA: 1, teamB: 14, lanePairIndex: 9 }, { teamA: 7, teamB: 12, lanePairIndex: 10 }, { teamA: 5, teamB: 10, lanePairIndex: 11 }],
            [{ teamA: 4, teamB: 21, lanePairIndex: 0 }, { teamA: 2, teamB: 23, lanePairIndex: 1 }, { teamA: 8, teamB: 17, lanePairIndex: 2 }, { teamA: 6, teamB: 19, lanePairIndex: 3 }, { teamA: 20, teamB: 13, lanePairIndex: 4 }, { teamA: 18, teamB: 15, lanePairIndex: 5 }, { teamA: 24, teamB: 9, lanePairIndex: 6 }, { teamA: 22, teamB: 11, lanePairIndex: 7 }, { teamA: 5, teamB: 12, lanePairIndex: 8 }, { teamA: 7, teamB: 10, lanePairIndex: 9 }, { teamA: 1, teamB: 16, lanePairIndex: 10 }, { teamA: 3, teamB: 14, lanePairIndex: 11 }],
            [{ teamA: 20, teamB: 22, lanePairIndex: 0 }, { teamA: 16, teamB: 10, lanePairIndex: 1 }, { teamA: 18, teamB: 24, lanePairIndex: 2 }, { teamA: 14, teamB: 12, lanePairIndex: 3 }, { teamA: 21, teamB: 19, lanePairIndex: 4 }, { teamA: 7, teamB: 1, lanePairIndex: 5 }, { teamA: 23, teamB: 17, lanePairIndex: 6 }, { teamA: 3, teamB: 5, lanePairIndex: 7 }, { teamA: 6, teamB: 4, lanePairIndex: 8 }, { teamA: 15, teamB: 9, lanePairIndex: 9 }, { teamA: 2, teamB: 8, lanePairIndex: 10 }, { teamA: 11, teamB: 13, lanePairIndex: 11 }],
            [{ teamA: 16, teamB: 12, lanePairIndex: 0 }, { teamA: 24, teamB: 20, lanePairIndex: 1 }, { teamA: 14, teamB: 10, lanePairIndex: 2 }, { teamA: 22, teamB: 18, lanePairIndex: 3 }, { teamA: 3, teamB: 7, lanePairIndex: 4 }, { teamA: 23, teamB: 19, lanePairIndex: 5 }, { teamA: 1, teamB: 5, lanePairIndex: 6 }, { teamA: 17, teamB: 21, lanePairIndex: 7 }, { teamA: 11, teamB: 15, lanePairIndex: 8 }, { teamA: 8, teamB: 4, lanePairIndex: 9 }, { teamA: 13, teamB: 9, lanePairIndex: 10 }, { teamA: 2, teamB: 6, lanePairIndex: 11 }],
            [{ teamA: 17, teamB: 9, lanePairIndex: 0 }, { teamA: 19, teamB: 11, lanePairIndex: 1 }, { teamA: 21, teamB: 13, lanePairIndex: 2 }, { teamA: 23, teamB: 15, lanePairIndex: 3 }, { teamA: 10, teamB: 2, lanePairIndex: 4 }, { teamA: 12, teamB: 4, lanePairIndex: 5 }, { teamA: 14, teamB: 6, lanePairIndex: 6 }, { teamA: 16, teamB: 8, lanePairIndex: 7 }, { teamA: 18, teamB: 1, lanePairIndex: 8 }, { teamA: 20, teamB: 3, lanePairIndex: 9 }, { teamA: 22, teamB: 5, lanePairIndex: 10 }, { teamA: 24, teamB: 7, lanePairIndex: 11 }],
            [{ teamA: 23, teamB: 13, lanePairIndex: 0 }, { teamA: 21, teamB: 15, lanePairIndex: 1 }, { teamA: 19, teamB: 9, lanePairIndex: 2 }, { teamA: 17, teamB: 11, lanePairIndex: 3 }, { teamA: 14, teamB: 8, lanePairIndex: 4 }, { teamA: 16, teamB: 6, lanePairIndex: 5 }, { teamA: 10, teamB: 4, lanePairIndex: 6 }, { teamA: 12, teamB: 2, lanePairIndex: 7 }, { teamA: 22, teamB: 7, lanePairIndex: 8 }, { teamA: 24, teamB: 5, lanePairIndex: 9 }, { teamA: 18, teamB: 3, lanePairIndex: 10 }, { teamA: 20, teamB: 1, lanePairIndex: 11 }],
            [{ teamA: 19, teamB: 15, lanePairIndex: 0 }, { teamA: 17, teamB: 13, lanePairIndex: 1 }, { teamA: 23, teamB: 11, lanePairIndex: 2 }, { teamA: 21, teamB: 9, lanePairIndex: 3 }, { teamA: 16, teamB: 4, lanePairIndex: 4 }, { teamA: 14, teamB: 2, lanePairIndex: 5 }, { teamA: 12, teamB: 8, lanePairIndex: 6 }, { teamA: 10, teamB: 6, lanePairIndex: 7 }, { teamA: 24, teamB: 3, lanePairIndex: 8 }, { teamA: 22, teamB: 1, lanePairIndex: 9 }, { teamA: 20, teamB: 7, lanePairIndex: 10 }, { teamA: 18, teamB: 5, lanePairIndex: 11 }],
            [{ teamA: 21, teamB: 11, lanePairIndex: 0 }, { teamA: 23, teamB: 9, lanePairIndex: 1 }, { teamA: 17, teamB: 15, lanePairIndex: 2 }, { teamA: 19, teamB: 13, lanePairIndex: 3 }, { teamA: 12, teamB: 6, lanePairIndex: 4 }, { teamA: 10, teamB: 8, lanePairIndex: 5 }, { teamA: 16, teamB: 2, lanePairIndex: 6 }, { teamA: 14, teamB: 4, lanePairIndex: 7 }, { teamA: 20, teamB: 5, lanePairIndex: 8 }, { teamA: 18, teamB: 7, lanePairIndex: 9 }, { teamA: 24, teamB: 1, lanePairIndex: 10 }, { teamA: 22, teamB: 3, lanePairIndex: 11 }]
        ]
    }
};
